/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fmod.hpp>

using namespace FMOD;

/* Header for class com_audioeffect_voicechanger_bridge_VoiceUtil */

#ifndef _Included_com_audioeffect_voicechanger_bridge_VoiceUtil
#define _Included_com_audioeffect_voicechanger_bridge_VoiceUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_NORMAL
#define com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_NORMAL 0L
#undef com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_LOLITA
#define com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_LOLITA 1L
#undef com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_UNCLE
#define com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_UNCLE 2L
#undef com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_THRILLER
#define com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_THRILLER 3L
#undef com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_FUNNY
#define com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_FUNNY 4L
#undef com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_ETHEREAL
#define com_audioeffect_voicechanger_bridge_VoiceUtil_MODE_ETHEREAL 5L
/*
 * Class:     com_audioeffect_voicechanger_bridge_VoiceUtil
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */

void setChannel(System *system, Sound *sound, int type);

JNIEXPORT int JNICALL Java_com_audioeffect_voicechanger_bridge_VoiceUtil_init(JNIEnv *env, jclass jcls, jstring path_jstr);

JNIEXPORT void JNICALL Java_com_audioeffect_voicechanger_bridge_VoiceUtil_fix
        (JNIEnv *, jclass, jint);
JNIEXPORT void JNICALL Java_com_audioeffect_voicechanger_bridge_VoiceUtil_stop
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_audioeffect_voicechanger_bridge_VoiceUtil_pause
        (JNIEnv *, jclass, jboolean is_paused);
JNIEXPORT void JNICALL Java_com_audioeffect_voicechanger_bridge_VoiceUtil_record
        (JNIEnv *, jclass, jstring path_jstr, jstring outputPath, jint type);

JNIEXPORT void JNICALL Java_com_audioeffect_voicechanger_bridge_VoiceUtil_pitch
        (JNIEnv *, jclass, jfloat pitch);

JNIEXPORT void JNICALL Java_com_audioeffect_voicechanger_bridge_VoiceUtil_seekToPercent
        (JNIEnv *, jclass, jfloat progress);

JNIEXPORT void JNICALL Java_com_audioeffect_voicechanger_bridge_VoiceUtil_release
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
